In [1]:
from Modules import Visualizer

vis = Visualizer("20221118_cid_freq_srs.csv")

In [19]:
vis.data.keys()

Index(['사고명', '사고일시', '공공민간구분', '날씨', '온도', '습도', '시설물 분류', '시설물 중분류',
       '시설물 소분류', '연면적', '지상층수', '지하층수', '공사종류', '인적사고종류', '안전방호조치여부',
       '개인보호조치여부', '물적사고종류', '공종(대분류)', '공종(소분류)', '사고객체(대분류)', '사고객체(소분류)',
       '작업프로세스', '사고위치 장소', '사고위치 장소(직접입력)', '사고위치 부위', '사고위치 부위(직접입력)',
       '주원인 유형', '사고원인(주원인)', '사고원인(보조원인1)', '사고원인(보조원인2)', '구체적사고원인', '사망자',
       '내국인 사망자', '외국인 사망자', '남성 사망자', '여성 사망자', '10이상 20미만 사망자',
       '20이상 30미만 사망자', '30이상 40미만 사망자', '40이상 50미만 사망자', '50이상 60미만 사망자',
       '60이상 사망자', '부상자', '내국인 부상자', '외국인 부상자', '남성 부상자', '여성 부상자',
       '10이상 20미만 부상자', '20이상 30미만 부상자', '30이상 40미만 부상자', '40이상 50미만 부상자',
       '50이상 60미만 부상자', '60이상 부상자', '피해금액', '피해내용', '사고신고사유', '공사비',
       '해당공종 공사비', '공사시작일', '공사종료일', '해당공종 공사시작일', '해당공종 공사종료일', '낙찰율', '공정율',
       '작업자수', '안전관리계획', '설계안정성검토', '사고조사방법', '향후조치계획', '사고경위', '사고발생후 조치사항',
       '재발방지대책', 'Month', 'Time', '사고종류', '공종', '공사규모_0-5', '공사규모_5-10',
       '공사규모_10-30', '공사규모_30-50', '공사규모_50-100', '공사규모_100-500',
       '공사규모_500-1000', '공사규모_1000-', '공사기간', 'construction_id', 'seriousness',
       'frequency'],
      dtype='object')

In [6]:
params = {
    "사고명" : "골절",
    "공공민간구분" : "민간"
}
vis.select_data(params)

,사고명,사고일시,공공민간구분,날씨,온도,습도,시설물 분류,시설물 중분류,시설물 소분류,연면적,...,공사규모_10-30,공사규모_30-50,공사규모_50-100,공사규모_100-500,공사규모_500-1000,공사규모_1000-,공사기간,construction_id,seriousness,frequency
13930,골절,2022-06-28 15:10,민간,맑음,33.0,65.0,기타 건축,건축물,창고시설,2100,...,0.0,0.0,0.0,0.0,0.0,0.0,9830.0,0.0,3.0,4.0
11963,골절,2022-01-20 12:20,민간,맑음,1.0,40.0,공동주택,건축물,공동주택,124838,...,0.0,0.0,0.0,0.0,0.0,1.0,956.0,7839.0,3.0,4.0
12121,골절,2022-02-10 12:00,민간,맑음,1.0,40.0,공동주택,건축물,공동주택,124838,...,0.0,0.0,0.0,0.0,0.0,1.0,914.0,7855.0,3.0,4.0
10563,골절,2021-10-12 10:40,민간,맑음,16.0,35.0,기타 건축,건축물,위락시설,9229.29,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,7968.0,3.0,4.0
9020,골절,2021-06-22 14:15,민간,흐림,23.0,55.0,공동주택,건축물,공동주택,42406,...,0.0,0.0,0.0,0.0,1.0,0.0,563.0,8434.0,3.0,4.0
9829,골절,2021-08-15 10:00,민간,맑음,29.0,75.0,기타 건축,건축물,교육연구시설,19964.96,...,0.0,0.0,0.0,1.0,0.0,0.0,200.0,10243.0,3.0,4.0
14155,골절,2022-07-22 09:40,민간,흐림,25.1,60.0,기타 건축,건축물,창고시설,70464,...,0.0,0.0,0.0,0.0,1.0,0.0,711.0,10935.0,3.0,4.0
12996,골절,2022-04-20 08:10,민간,맑음,10.0,65.0,기타 건축,건축물,업무시설,16795.38,...,0.0,0.0,0.0,1.0,0.0,0.0,425.0,11436.0,3.0,1.0

In [2]:
import numpy as np
type(vis.data["온도"][0]) == np.float64

True

In [11]:
vis.data.dtypes["온도"]

AttributeError: 'numpy.dtype[float64]' object has no attribute 'is_float'

In [13]:
import pandas as pd
pd.api.types.is_float_dtype(vis.data.dtypes["온도"])

True

In [16]:
for key in vis.data.keys():
    print(type(vis.data[key][0]) )

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>

False